#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
git diff --cached --quiet --exit-code && exit 0
git diff --cached --binary --no-ext-diff | "$SCRIPT_DIR/trufflehog-scan"
